final List<String> marutiSuzukiMake = [
  '1000',
  '800',
  'Alto 800',
  'Alto',
  'Alto K10',
  'A-Star',
  'Baleno',
  'Brezza',
  'Celerio',
  'Celerio X',
  'Ciaz',
  'Dzire',
  'Eeco',
  'Ertiga',
  'Esteem',
  'Estilo',
  'Grand Vitara',
  'Gypsy',
  'Ignis',
  'Kizashi',
  'Omni',
  'Ritz',
  'S-Cross',
  'S-Presso',
  'Stingray',
  'Swift',
  'Swift Dzire',
  'SX4',
  'Versa',
  'Vitara Brezza',
  'Wagon R',
  'Wagon R 1.0',
  'XL6',
  'Zen'
];

final List<String> hyundaiMake = [
  'Accent',
  'Viva',
  'Alcazar',
  'Aura',
  'Creta',
  'Elantra',
  'Elite i20',
  'Eon',
  'Fluidic Verna 4S',
  'Getz',
  'Getz Prime',
  'Grand i10',
  'Grand i10 Nios',
  'i10',
  'i20',
  'i20 Active',
  'i20 N Line',
  'Kona Electric',
  'Santa Fe',
  'Santro',
  'Santro Xing',
  'Sonata',
  'Sonata Embera',
  'Sonata Transform',
  'Terracan',
  'Tucson',
  'Venue',
  'Venue N Line',
  'Verna',
  'Verna 2020',
  'Verna Transform',
  'Xcent'
];

final List<String> hondaMake = [
  'Accord',
  'Amaze',
  'Brio',
  'BR-V',
  'City',
  'All New City',
  'City Hybrid eHEV',
  'City ZX',
  'Civic',
  'Concerto',
  'CR-V',
  'CR-X',
  'Jazz',
  'Mobilio',
  'Step WGN',
  'WR-V',
];
final List<String> fordMake = [
  'Aspire',
  'Capri',
  'Classic',
  'EcoSport',
  'Endeavour',
  'Escort',
  'Fiesta',
  'Fiesta Classic',
  'Figo',
  'Freestyle',
  'Fusion',
  'Ikon',
  'Model T',
  'Mondeo',
  'Mustang',
  'Raptor',
  'Zephyr',
];

final List<String> mahindraMake = [
  'Alturas G4',
  'Armada',
  'Bolero',
  'Bolero Neo',
  'e2o',
  'e2o PLUS',
  'Jeep',
  'KUV100',
  'KUV100 NXT',
  'Marazzo',
  'Marshal',
  'NuvoSport',
  'Quanto',
  'REVAi',
  'Scorpio',
  'Scorpio 2021',
  'Scorpio Getaway',
  'Scorpio N',
  'Thar',
  'TUV300',
  'Verito',
  'Verito Vibe CS',
  'Voyager',
  'XUV300',
  'XUV300 TurboSport',
  'XUV500',
  'XUV700',
  'Xylo',
];

final List<String> mitsubishiMake = [
  'Cedia',
  'Challenger',
  'FTO',
  'Galant',
  'GTO',
  'Lancer',
  'Lancer Evolution',
  'Montero',
  'Outlander',
  'Pajero',
  'Pajero Sport',
];

final List<String> fuelType = ['Petrol', 'Diesel', 'CNG', 'Electric'];
final List<String> seatCapacity = ['2', '4', '5', '6', '8', '10'];

Map<String, List<String>> carDataset = {
  'Maruti Suzuki': marutiSuzukiMake,
  'Honda': hondaMake,
  "Hyundai": hyundaiMake,
  'Mitsubishi': mitsubishiMake,
  'Mahindra': mahindraMake
};
